name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.3
  cupertino_icons: ^1.0.8
  syncfusion_flutter_charts: ^29.2.4
  image_picker: ^1.1.2
  cloud_firestore: ^4.0.0
  firebase_storage: ^11.0.0
  percent_indicator: ^4.2.5
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  intl: ^0.20.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/avatars/avatar1.png
    - assets/avatars/avatar2.png
    - assets/avatars/avatar3.png
    - assets/avatars/avatar4.png
    - assets/avatars/avatar5.png
    - assets/avatars/avatar6.png
    - assets/avatars/avatar7.png
    - assets/avatars/avatar8.png
    - assets/avatars/avatar9.png
    - assets/avatars/avatar10.png
    - assets/avatars/avatar11.png
    - assets/avatars/avatar12.png
    - assets/avatars/avatar13.png
    - assets/avatars/avatar14.png
    - assets/avatars/avatar15.png
    - assets/avatars/avatar16.png
    - assets/avatars/avatar17.png
    - assets/avatars/avatar18.png
    - assets/avatars/avatar19.png
    - assets/avatars/avatar20.png
    - assets/avatars/avatar21.png
    - assets/avatars/avatar22.png
    - assets/avatars/avatar23.png
    - assets/images/finance_icon.png
